Controllers/DemoWalletController.cs
using System.Linq;
using Binance.Net.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StrzonBinanceTradingBot.Helpers;
using StrzonBinanceTradingBot.Models;
using StrzonBinanceTradingBot.Services;

namespace StrzonBinanceTradingBot.Controllers;

[Authorize]
public class DemoWalletController : Controller
{
    private readonly ILogger<DemoWalletController> _logger;
    private readonly IBinanceClient _binanceClient;
    private readonly IBalanceService _balanceService;
    private readonly IDemoWalletService _demoWalletService;
    private readonly ITradeService _tradeService;
    private readonly Settings _settings;

    public DemoWalletController(
        ILogger<DemoWalletController> logger,
        IBinanceClient binanceClient,
        IBalanceService balanceService,
        IDemoWalletService demoWalletService,
        Settings settings,
        ITradeService tradeService)
    {
        _logger = logger;
        _binanceClient = binanceClient;
        _balanceService = balanceService;
        _demoWalletService = demoWalletService;
        _settings = settings;
        _tradeService = tradeService;
    }

    public IActionResult Index()
    {
        var model = new DemoWalletIndexViewModel();
        ViewBag.UpdateInterval = _settings.scheduledTaskInterval;
        return View(model);
    }

    public IActionResult ResetWallet()
    {
        var username = User.Identity?.Name ?? "";
        var wallet = _demoWalletService.GetOrCreate(username);
        if (wallet == null)
        {
            throw new ArgumentNullException("There is no wallet for this user");
        }
        _demoWalletService.DeleteDemoWallet(wallet.Id);
        _demoWalletService.Create(0, username);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult GetPerformanceChart()
    {
        var response = new PerformanceGraphData();
        try
        {
            var username = User.Identity?.Name ?? "";
            var wallet = _demoWalletService.GetOrCreate(username);
            if (wallet == null)
            {
                throw new ArgumentNullException("There is no wallet for this user");
            }

            var history = _balanceService.GetBalanceHistory(wallet.Id);
            var reducedHistory = new List<Data.BalanceHistoryEntity>();

            if (history != null)
            {
                for (int i = 0; i < history.Count(); i++)
                {
                    if (i <= 0 || (history[i].TotalBalanceInUSDT != history[i - 1].TotalBalanceInUSDT))
                    {
                        reducedHistory.Add(history[i]);
                    }
                }

                response.labels = reducedHistory.Select(x => x.Date.ToString("yyyy-MM-dd HH:mm")).ToArray();

                var uds = new ChartDecimalDataSet
                {
                    label = "USDT",
                    data = reducedHistory.Select(x => x.TotalBalanceInUSDT).ToArray()
                };
                response.datasets = new ChartDecimalDataSet[] { uds };
            }
        }
        catch (Exception ex)
        {
            response.Error = new ErrorViewModel
            {
                ErrorCode = "GetPerformanceChart",
                Message = ex.Message
            };
        }

        return Json(response);
    }

    public IActionResult GetTrades()
    {
        var response = new TradesViewModel();

        try
        {
            var username = User.Identity?.Name ?? "";
            var wallet = _demoWalletService.GetOrCreate(username);
            if (wallet == null)
            {
                throw new ArgumentNullException("There is no wallet for this user");
            }

            var trades = _tradeService.TradesOfDemoWallet(wallet.Id);
            response.Trades = trades?.Select(x => new TradeViewModel
            {
                Date = x.Date,
                Symbol = x.Symbol,
                Amount = x.Amount,
                Price = x.USDTRate,
                Total = x.AmountInUSDT,
                Type = Enum.GetName(x.Type.GetType(), x.Type)
            }).ToList();
            response.IsSuccess = true;
        }
        catch (Exception ex)
        {
            response.Error = new ErrorViewModel
            {
                ErrorCode = "GetTrades",
                Message = ex.Message
            };
        }

        return Json(response);
    }

    [HttpPost]
    public IActionResult StopLockInProfits(string[] symbols)
    {
        var response = new ResponseViewModel();

        if (symbols == null || symbols.Length <= 0)
        {
            return Json(response);
        }

        try
        {
            var username = User.Identity?.Name ?? "";
            var wallet = _demoWalletService.GetOrCreate(username);
            if (wallet == null)
            {
                throw new ArgumentNullException("There is no wallet for this user");
            }

            _balanceService.Unlock(symbols, wallet.Id, username);
            response.IsSuccess = true;
        }
        catch (Exception ex)
        {
            response.Error = new ErrorViewModel
            {
                ErrorCode = "StopLockInProfits",
                Message = ex.Message
            };
        }

        return Json(response);
    }

    [HttpPost]
    public IActionResult LockInProfits(string[] symbols)
    {
        var response = new ResponseViewModel();

        if (symbols == null || symbols.Length <= 0)
        {
            return Json(response);
        }

        try
        {
            var username = User.Identity?.Name ?? "";
            var wallet = _demoWalletService.GetOrCreate(username);
            if (wallet == null)
            {
                throw new ArgumentNullException("There is no wallet for this user");
            }

            _balanceService.Lock(symbols, wallet.Id, username);
            response.IsSuccess = true;
        }
        catch (Exception ex)
        {
            response.Error = new ErrorViewModel
            {
                ErrorCode = "LockInProfits",
                Message = ex.Message
            };
        }

        return Json(response);
    }

    [HttpPost]
    public async Task<IActionResult> AddCoinToWallet(string symbol, decimal amount)
    {
        var response = new ResponseViewModel();

        var username = User.Identity?.Name ?? "";

        try
        {
            var wallet = _demoWalletService.GetOrCreate(username);
            if (wallet == null)
            {
                throw new ArgumentNullException("There is no wallet for this user");
            }

            var priceResponse = await _binanceClient.Spot.Market.GetPriceAsync($"{symbol}USDT");
            if (!priceResponse.Success)
            {
                _logger.LogError("UpdateBalance Error");
                response.Error = new ErrorViewModel
                {
                    ErrorCode = priceResponse.Error?.Code.ToString(),
                    Message = priceResponse.Error?.Message
                };
            }
            else
            {
                var price = priceResponse.Data.Price;

                var balance = _balanceService.Get(symbol, wallet.Id, username);
                if (balance == null)
                {
                    _balanceService.Add(symbol, amount, price, wallet.Id, username);
                }
                else
                {
                    _balanceService.Update(symbol, wallet.Id, username, price, amount, Data.BalanceHistoryEntity.Action.Update);
                }
                response.IsSuccess = true;
            }
        }
        catch (Exception ex)
        {
            response.Error = new ErrorViewModel
            {
                ErrorCode = "AddCoinToWallet",
                Message = ex.Message
            };
        }

        return Json(response);
    }

    public IActionResult GetCoins()
    {
        var response = new CoinsViewModel();
        var username = User.Identity?.Name ?? "";
        try
        {
            var wallet = _demoWalletService.GetOrCreate(username);
            if (wallet == null)
            {
                throw new ArgumentNullException("There is no wallet for this user");
            }

            var balances = _balanceService.GetBalancesOfWallet(wallet.Id, username);
            response.Coins = balances?.Select(x => new CoinViewModel
            {
                Coin = x.Symbol,
                Amount = x.Amount,
                Price = x.USDTRate,
                LockedPrice = x.LockUSDTRate,
                IsLocked = x.IsLocked,
            }).ToList();
            response.IsSuccess = true;
        }
        catch (Exception ex)
        {
            _logger.LogError("GetCoins Error");
            response.Error = new ErrorViewModel
            {
                ErrorCode = "GetCoins",
                Message = ex.Message
            };
        }

        return Json(response);
    }

    public async Task<IActionResult> GetPrices()
    {
        var response = new PricesViewModel();
        var pricesResponse = await _binanceClient.Spot.Market.GetPricesAsync();
        if (pricesResponse.Success)
        {
            response.Prices = pricesResponse.Data
                                            .Where(x => x.Symbol.Contains("USDT"))
                                            .Select(x => new PriceViewModel
                                            {
                                                Price = x.Price,
                                                Symbol = x.Symbol
                                            })
                                            .ToList();
            response.IsSuccess = true;
        }
        else
        {
            _logger.LogError("GetPrices");
            response.Error = new ErrorViewModel
            {
                ErrorCode = pricesResponse.Error?.Code.ToString(),

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pixfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StrzonBinanceTradingBot.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pixfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DemoWallet" asp-action="Index">Demo Wallet</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - pixfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js" 
        integrity="sha512-QSkVNOCYLtj73J4hbmVoOV6KVZuMluZlioC+trLpewV8qMjsWqlIQvkn1KGX2StWvPMdWGBqim1xlC8krl1EKQ==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>  
    @* <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.esm.min.js" 
        integrity="sha512-ESlgC6ZyzTZdmD7XoDrXJNOqoIugH+FNKg8nAk8sa3cZfFALiV+lo5xoia649oyygwnkKsdUdPAJ+puqGbOs+g==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/helpers.esm.min.js" 
        integrity="sha512-urWBnIv+F027G24xDNigjxvIuwnWlWy94W2yx77VkISKLzKSohOKOubMDhtEF6LZcEH7gctmNSpxDqIW/zMmUg==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script> *@

</body>
</html>